### ISSUE TITLE
prefer `sky_tools foo` or `sky_tools:foo`?

### ISSUE THREAD

**Issue by devoncarew** [domokit/sky_tools#2]
Is there any preference for one entry-point taking multiple commands, or many entry-points each implementing one command? As in, do we want:

```
sky_tools serve
sky_tools build_apk
sky_tools create_project
```

or

```
sky_tools:serve
sky_tools:build_apk
sky_tools:create_project
```

One way has one script in `bin/` and the other has many scripts in `bin/`.

**Comment by devoncarew** [comment]
@abarth

**Comment by abarth** [comment]
Up to you.  Whatever you think is best.

**Comment by devoncarew** [comment]
OK, going with `skytools init` for now -
