### ISSUE TITLE
publish 0.0.8 of sky_tools

### ISSUE THREAD

**Issue by devoncarew** [domokit/sky_tools#8]
This will let us capture the new `init` command; the pubspec version has already been rev'd.

@abarth

**Comment by abarth** [comment]
@devoncarew I've added you as an uploader for the package.  Please keep in mind that Sky developers have their pubspecs set to pick up the latest version of this package so we need to make sure not to break them.  (Currently they're using only the sky_server command.)

**Comment by devoncarew** [comment]
> have their pubspecs set to pick up the latest version of this package 

Will do. Once things settle down a bit, we should encourage users to depend on this package with a version range (`^0.1.0`, `^1.0.0`, ...) so we have a bit more flexibility wrt breaking changes.

**Comment by abarth** [comment]
The `sky` package does indicate a version range for `sky_tools`.  Hopefully that helps.

**Comment by devoncarew** [comment]
Published!
